Feature/autoencoder
beckstev/MachineLearningSeminar pull request #33
Opened 2019-06-30 10:46 UTC by beckstev

Implemented alternative method based on an autoencoder and a random forest. 

__Pipeline:__
Image  &rightarrow; Get rescaled by dataloader &rightarrow; Put into encoder to generate feature map &rightarrow;  Put into random forest

__HOW TO TEST:__
Train autoencoder and random forest 
`python train_autoencoder.py <label_encoder> <img_resize as width height>`

Visual evauation of the alternative method:
 `python eval_alt_method.py <label_encoder> <img_resize as width height>`

2019-06-30 18:21 UTC, FeGeyer requested changes
Konnte es leider nicht testen, da beim Ausführen der `train_autoencoder` Datei folgender Fehler auftrat:
`module 'dog_classifier.autoencoder' has no attribute 'randomforest'`, wenn in `evaluate_training` die Importierung durchgeführt wird. Umbenennen der Ordnerstruktur und der files half leider nicht, ebenso ein direktes importieren der benötigten Funktion `get_encoder` aus der Datei `randomforest.py`. Jedes Mal endet es damit, dass diese Datei nicht gefunden wird. Selbst ein Neuinstallieren des Frameworks hat nicht geholfen. Bin mit meinem Latein am Ende.... Hast du etwas geändert oder diesen Fehler vielleicht selbst gehabt?

2019-06-30 18:21 UTC, FeGeyer commented on dog_classifier/evaluate/evaluate_training.py
> +def model_loader(path_to_model, main_model, checkpoint_model):
Einfach ausgelagert, um es modularer zu gestalten oder?

2019-06-30 18:25 UTC, FritzGeise commented
Klingt jetzt voll negativ, bin eigentlich super zufrieden mit deiner Arbeit, hast du klasse gemacht! Leider kann ich es nur nicht durchlaufen lassen bei mir...

2019-07-02 06:18 UTC, beckstev commented on dog_classifier/evaluate/evaluate_training.py
> +def model_loader(path_to_model, main_model, checkpoint_model):
Yes, because I want to have the same functionality for the autoencoder

2019-07-02 06:33 UTC, beckstev commented
@FritzGeise  bug fix, you should now be able to load the package.

2019-07-04 11:27 UTC, FeGeyer approved these changes

2019-07-04 11:28 UTC, merged