Feature/eval hyper tuning
beckstev/MachineLearningSeminar pull request #40
Opened 2019-07-08 14:13 UTC by beckstev

Added script to analyze the hyperparamter tuning. 

__How to test__
`python eval_hyper_tuning.py <path to model>`

Please be aware that your model need a `hyper_param_tuning` directory which will be generated automatically during the hyper tuning. I can hand you a test directory tomorrow.

2019-07-09 12:52 UTC, FeGeyer requested changes
Good job, only switching from learning_rate to use_rgb is missing

2019-07-10 21:02 UTC, beckstev commented
@FritzGeise 
Please find your requested changes in my latest commits.

2019-07-11 09:31 UTC, FeGeyer approved these changes
Hab die Ordnerbezeichung noch geändert und die learning rate wieder auf den Standard Wert gesetzt, der Rest war gut.

2019-07-11 09:31 UTC, FritzGeise commented on scripts/hyper_tuning.py
> -    if args.use_rgb:
Brauchen wir das in der `training.py` eigentlich noch? Das wird meiner Ansicht nach nirgendwo verwertet...

2019-07-11 10:16 UTC, merged